# FROM alpine:3.4
FROM mhart/alpine-node:latest

RUN apk add --update nodejs bash git

ADD ./backend /backend
ADD ./frontend /frontend

ENV docker_env "true"
ENV prod_env "true"

RUN cd /frontend && \
npm install && \
npm run build-prod && \
mv /frontend/dist /dist && \
rm -r /frontend && \
cd /backend && \
npm install && \
npm run build

ENV PORT 8080
EXPOSE $PORT


WORKDIR /backend

CMD [ "npm", "run", "run-docker"]
# CMD [ "npm", "run", "install" ];
# CMD [ "npm", "run", "start" ];




