version: '3'
services:
  backend-server:
    build: 
      context: ./backend/
    volumes:
    - ./backend:/backend
    ports:
    - "8080:8080"
    links:
    - mongo
    environment:
    - "db_url=mongodb://mongo/test"
    - "server_port=8080"
    - "auth_enabled=${auth}"
  mongo:
    image: mongo:latest
    volumes:
    - mdb:/data/db
    - mdbc:/data/configdb
    ports:
    - "27017:27017"
  frontend-server:
    build: 
      context: ./frontend/
    volumes:
    - ./frontend:/frontend
    ports:
    - "8000:8000"
volumes:
  mdb:
  mdbc:

