version: '3'
services:
  backend-server:
    build:
      context: ../../backend/
    volumes:
    - ../../backend:/backend
    ports:
    - "8080:8080"
    links:
    - persistence-mongo-dev
    environment:
    - "db_url=mongodb://persistence-mongo-dev/test"
    - "server_port=8080"
    - "auth_enabled=${auth}"
  persistence-mongo-dev:
    build:
      context: ./db/
    ports:
    - "27017:27017"
  frontend-server:
    build:
      context: ../../frontend/
    volumes:
    - ../../frontend:/frontend
    ports:
    - "8000:8000"
