version: '3'
services:
  mongo:
    image: mongo:latest
    volumes:
    - mdb:/data/db
    - mdbc:/data/configdb
    ports:
    - "27017:27017"
  prod-server:
    build:
      context: ../../
      dockerfile: ./deploy/prod/Dockerfile
    ports:
    - "8080:8080"
    links:
    - mongo
    environment:
    - "db_url=mongodb://mongo/test"
    - "production=true"
    - "server_port=8080"
volumes:
  mdb:
  mdbc:
