version: '3'
services:
  mongo:
    image: mongo:latest
    build: 
      context: ../dev/db/
    volumes:
    - mdb:/data/mongod
    - mdbc:/data/configdb
    ports:
    - "27017:27017"
  prod-server:
    build:
      context: ../../
      dockerfile: ./deploy/prod/Dockerfile
    ports:
    - "${server_port}:${server_port}"
    links:
    - mongo
    environment:
    - "db_url=mongodb://mongo/test"
    - "production=true"
    - "server_port=${server_port}"
    - "auth_enabled=${auth}"
    - "api_url=${protocol}://${server_domain}:${server_port}/api"
volumes:
  mdb:
  mdbc:
